### ISSUE TITLE
Limited support for share types

### ISSUE THREAD

**Issue by jcaputo4** [Banno/banno-powerons#95]
BANNO.ODTOPTIN.V1.POW

The repgen/config only supports 1,000 share types, we need at least 2,000, but really it should support all available 10,000 types in Symitar.

The repgen appears to use an array for eligible types, because of list expansion.  Probably a bad approach for 10,000 possible types.

**Comment by tkainz** [comment]
The Power on does handle all possible Share Types (0000-9999); the issue is with incorrect documentation which should be corrected shortly.

**Comment by tkainz** [comment]
Configuration Letter file has been updated and submitted for peer review. README.md and JSON contracts have been updated and additional info added as well.
